version: '3.9'
services:
  db:
    build:
      context: ./
      dockerfile: ./mongo.Dockerfile
    ports:
      - '27017:27017'
  api:
    build:
      context: ./
      dockerfile: ./server.Dockerfile
    ports:
      - '8080:8080'
